language: node_js
os:
  - linux
  - osx
cache:
  directories:
    - ~/.npm  
notifications:
  email: true
node_js:
  - 'node'
  - '6'  
install:
  - npm install
script:
  - npm run test
  - npm run build
after_success:
  - npm run travis
